import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  Sidebar1: [{type: 'autogenerated', dirName: '现代文学'}],
  Sidebar2: [{type: 'autogenerated', dirName: '当代文学'}],
  Sidebar3: [{type: 'autogenerated', dirName: '现代汉语'}],
  Sidebar4: [{type: 'autogenerated', dirName: '公文写作'}],
  Sidebar5: [{type: 'autogenerated', dirName: '先秦文学'}],
  Sidebar6: [{type: 'autogenerated', dirName: '唐宋文学'}],
  Sidebar7: [{type: 'autogenerated', dirName: '元明清文学'}],
  Sidebar8: [{type: 'autogenerated', dirName: '关于我们'}],
};

export default sidebars;
